name: Playwright Parallel Tests

on: push

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.21.3]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install library
      run: |
        npm i
        npx playwright install

  test:
    needs: build
    strategy:
      matrix:
        test_suite: ["login", "customer"]
    runs-on: ubuntu-latest
     steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install library
      run: |
        npm i
        npx playwright install

      - name: Install Dependencies
        run: npm install

      - name: Run Tests for ${{ matrix.test_suite }} Suite
        run: npx playwright test tests/${{ matrix.test_suite }}
